import Footer from "@/components/Footer/Footer";
import AuthProvider from "@/components/providers/AuthProvider";
import { colors } from "@/public/colors/colors";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          padding: 0,
          boxSizing: "border-box",
          backgroundColor: colors.white,
        }}
        className={montserrat.className}
      >
        <AuthProvider>
          <div
            style={{
              padding: "0 14px 80px 14px",
            }}
          >
            {children}
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
